# Generated by Django 6.0.5 on 2026-06-01 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('name_az', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('name_az', models.CharField(max_length=100, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Техника',
                'verbose_name_plural': 'Техники',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название работы')),
                ('title_ru', models.CharField(max_length=120, null=True, verbose_name='Название работы')),
                ('title_en', models.CharField(max_length=120, null=True, verbose_name='Название работы')),
                ('title_az', models.CharField(max_length=120, null=True, verbose_name='Название работы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_az', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('main_image', models.ImageField(upload_to='paintings/', verbose_name='Главное фото')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год')),
                ('dimensions', models.CharField(blank=True, max_length=100, verbose_name='Размеры')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paintings', to='main.category', verbose_name='Категория')),
                ('technique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paintings', to='main.technique', verbose_name='Техника')),
            ],
            options={
                'verbose_name': 'Картина',
                'verbose_name_plural': 'Картины',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaintingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='paintings/gallery/', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('painting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.painting', verbose_name='Картина')),
            ],
            options={
                'verbose_name': 'Доп. фото',
                'verbose_name_plural': 'Доп. фото',
                'ordering': ['order'],
            },
        ),
    ]
