# Generated by Django 6.0.5 on 2026-06-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=150, unique=True, verbose_name='Ключ')),
                ('text_ru', models.CharField(blank=True, max_length=500, verbose_name='Русский')),
                ('text_en', models.CharField(blank=True, max_length=500, verbose_name='English')),
                ('text_az', models.CharField(blank=True, max_length=500, verbose_name='Azərbaycan')),
            ],
            options={
                'verbose_name': 'Перевод интерфейса',
                'verbose_name_plural': 'Переводы интерфейса',
                'ordering': ['key'],
            },
        ),
    ]
